### ISSUE TITLE
./orbitdb/identity/identitykeys/LOCK: already held by process

### ISSUE THREAD

**Issue by alexander-lipnitskiy** [orbitdb/orbit-db#629]
Hi. I am developing node.js server application. Some data from queries I put in orbitdb.
When the server receives many queries, I can see the following error:

UnhandledPromiseRejectionWarning: OpenError: IO error: lock ./orbitdb/identity/identitykeys/LOCK: already held by process

    at .../node_modules/levelup/lib/levelup.js:87:23
    at .../node_modules/abstract-leveldown/abstract-leveldown.js:30:14
    at .../node_modules/deferred-leveldown/deferred-leveldown.js:20:21
    at .../node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:41:14

Library versions:
"orbit-db": "^0.21.0-rc.1"
"orbit-db-identity-provider": "^0.1.2-rc.1.2"
"ipfs": "^0.35.0"
"ipfs-http-client": "^30.1.3"

**Comment by aphelionz** [comment]
Hi there rc1 is a little old now. Please try `latest` or `next`

**Comment by alexander-lipnitskiy** [comment]
I have still this error, I try many different versions of orbit-db. No one version still couldn't resolve this error.

**Comment by BartKnucle** [comment]
Still have the issue with the 0.21.0-rc.1 too.

**Comment by shamb0t** [comment]
@alexander-lipnitskiy @BartKnucle thanks for reporting! Leveldb is trying to access a directory thats in already use. Does this occur when simply opening a db with content? Can you provide the code which gives the error?

**Comment by alexander-lipnitskiy** [comment]
This happens when I receive simultaneously several post requests to a nodejs server for different endpoints, each endpoint saves data to orbitdb. 

Does this occur when simply opening a db with content?
I don't have this issue with simple operations.

**Comment by alexander-lipnitskiy** [comment]
This is a simplified example of how I put data in orbitdb. 

    for await (let item of req.body) {
        try {
            await orbitDB.put(item);
        } catch (err) {
            console.error(`${err}\n`);
            return;
        }
    }
    res.status(200).send('ok');

**Comment by aphelionz** [comment]
Hi Alexander, this might be the problem im currently looking into now. Can you try with the `fix/persistent-store` branch

**Comment by BartKnucle** [comment]
@aphelionz @shamb0t My mistake, didn't apply the patch after update to 0.21.0-rc.1. Patch still working 👍

**Comment by BartKnucle** [comment]
But I have the following errors: 

```this._store.put is not a function                                                                                                                                                                  10:16:39

  at Keystore.createKey (node_modules\orbit-db-keystore\src\keystore.js:97:25)
  at process._tickCallback (internal/process/next_tick.js:68:7)
this._store.put is not a function                                                                                                                                                                  10:16:39

  at Keystore.createKey (node_modules\orbit-db-keystore\src\keystore.js:97:25)
  at process._tickCallback (internal/process/next_tick.js:68:7)```

**Comment by BartKnucle** [comment]
Ok my fault, I didn't apply the fix to all modules...

**Comment by BartKnucle** [comment]
Can't test on my side, I have to manage too many branches. (Windows one and fix persistent connection)

**Comment by RichardLitt** [comment]
@BartKnucle 	Could you try again? Is this still open?

**Comment by BartKnucle** [comment]
@RichardLitt, do you want me to try it on the 0.21.3 npm package? I have to integrate first the Windows support and will tell you somthing. :)

**Comment by RichardLitt** [comment]
Aye, that'd be great.

**Comment by aphelionz** [comment]
Closing this as people should be either using the v0.21.4 `latest` or 0.22.0-rc# `next`
